name=IntegerGlass
version=2.1
author=GitMoDu <batatas@gmail.com>
maintainer=GitMoDu <batatas@gmail.com>
sentence=Graphics framework and display engine for embedded systems.
paragraph=Template based embedded graphics framework, featuring fixed-point arithmetic and templated pixel shader pipeline.
category=Graphics
url=https://github.com/GitMoDu/IntegerGlass
architectures=*
